""" You are given two strings s and t.

String t is generated by random shuffling string s and
then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"

Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. """


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        list_s = list(s)
        list_s.sort()
        list_t = list(t)
        list_t.sort()

        if s == "":
            return t
        else:
            for chr1, chr2 in zip(list_s, list_t):
                if chr1 != chr2:
                    return chr2

            return list_t[-1]
